import sys

env = Environment()

env['CPPDEFINES'] = []
if sys.byteorder == "little":
   env['CPPDEFINES'].append(['BITS_LITTLE_ENDIAN'])

env['CPPFLAGS'] = []
env['CPPFLAGS'].append ( '-std=gnu++0x' )

#env['CPPFLAGS'].append ( '-g' )
#env['CPPFLAGS'].append ( '-pg' )

env.Library('bits', ['bits.cpp', 'bits-stream.cpp'])

#env.Program('bitstring-test.cpp', LIBS=['bitstring', 'cpptest'], LIBPATH='.')
#env.Program('mpegts-test.cpp', LIBS=['mpegts', 'bitstring', 'cpptest', 'PocoFoundation', 'PocoNet'], LIBPATH='.')
#env.Program('mpegts-xmit.cpp', LIBS=['mpegts', 'bitstring', 'cpptest', 'PocoFoundation', 'PocoNet', 'PocoUtil'], LIBPATH='.')

